module.exports =  {
    "results": [
        {
        "picks": [
        "Adam Driver, Marriage Story",
        "Tom Hanks, A Beautiful Day in the Neighborhood",
        "Scarlett Johansson, Marriage Story",
        "Margot Robbie, Bombshell",
        "Klaus",
        "The Lighthouse",
        "Little Women",
        "Once upon a Time...in Hollywood",
        "The Edge of Democracy",
        "St. Louis Superman",
        "Jojo Rabbit",
        "Parasite",
        "Joker",
        "Star Wars: The Rise of Skywalker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Once upon a Time...in Hollywood",
        "The Irishman",
        "Kitbull",
        "Brotherhood",
        "Ford v Ferrari",
        "Ad Astra",
        "The Lion King",
        "Jojo Rabbit",
        "Knives Out",
        12212
        ],
        "_id": "5e2847fd92e881001716cc8f",
        "username": "5e2847fd92e881001716cc8e",
        "date": "2020-01-22T13:02:53.576Z",
        "__v": 0
        },
        {
        "picks": [
        "Antonio Banderas, Pain and Glory",
        "Tom Hanks, A Beautiful Day in the Neighborhood",
        "Cynthia Erivo, Harriet",
        "Kathy Bates, Richard Jewell",
        "How to Train Your Dragon: The Hidden World",
        "The Irishman",
        "The Irishman",
        "The Irishman",
        "American Factory",
        "In the Absence",
        "Ford v Ferrari",
        "Corpus Christi",
        "Bombshell",
        "Joker",
        "I Can't Let You Throw Yourself Away, Toy Story 4",
        "Ford v Ferrari",
        "The Irishman",
        "Dcera (Daughter)",
        "Brotherhood",
        "Ford v Ferrari",
        "Ad Astra",
        "Avengers: Endgame",
        "The Irishman",
        "Knives Out",
        3841
        ],
        "_id": "5e2866fbdb93410017008634",
        "username": "5e2866fbdb93410017008633",
        "date": "2020-01-22T15:15:07.468Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Once upon a Time...in Hollywood",
        "1917",
        "American Factory",
        "In the Absence",
        "Ford v Ferrari",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Once upon a Time...in Hollywood",
        "Once upon a Time...in Hollywood",
        "Memorable",
        "Brotherhood",
        "1917",
        "1917",
        "The Lion King",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11048
        ],
        "_id": "5e2868efdb93410017008636",
        "username": "5e2868efdb93410017008635",
        "date": "2020-01-22T15:23:27.601Z",
        "__v": 0
        },
        {
        "picks": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
        ],
        "_id": "5e286963db9341001700863a",
        "username": "5e286963db93410017008639",
        "date": "2020-01-22T15:25:23.683Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Charlize Theron, Bombshell",
        "Scarlett Johansson, Jojo Rabbit",
        "Missing Link",
        "1917",
        "Joker",
        "1917",
        "Honeyland",
        "St. Louis Superman",
        "Parasite",
        "Parasite",
        "Joker",
        "Little Women",
        "Into The Unknown, Frozen II",
        "1917",
        "1917",
        "Hair Love",
        "Brotherhood",
        "1917",
        "Once upon a Time...in Hollywood",
        "1917",
        "Little Women",
        "Knives Out",
        13773
        ],
        "_id": "5e286909db93410017008638",
        "username": "5e286909db93410017008637",
        "date": "2020-01-22T15:23:53.170Z",
        "__v": 0
        },
        {
        "picks": [
        "Adam Driver, Marriage Story",
        "Tom Hanks, A Beautiful Day in the Neighborhood",
        "Charlize Theron, Bombshell",
        "Florence Pugh, Little Women",
        "Toy Story 4",
        "1917",
        "Little Women",
        "The Irishman",
        "American Factory",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Bombshell",
        "Marriage Story",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Once upon a Time...in Hollywood",
        "Kitbull",
        "Saria",
        "Star Wars: The Rise of Skywalker",
        "Ad Astra",
        "The Irishman",
        "The Two Popes",
        "Knives Out",
        12625
        ],
        "_id": "5e28697fdb9341001700863c",
        "username": "5e28697fdb9341001700863b",
        "date": "2020-01-22T15:25:51.906Z",
        "__v": 0
        },
        {
        "picks": [
        "Adam Driver, Marriage Story",
        "Anthony Hopkins, The Two Popes",
        "Scarlett Johansson, Marriage Story",
        "Scarlett Johansson, Jojo Rabbit",
        "Toy Story 4",
        "1917",
        "Little Women",
        "1917",
        "For Sama",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Joker",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Once upon a Time...in Hollywood",
        "Hair Love",
        "Nefta Football Club",
        "1917",
        "1917",
        "Avengers: Endgame",
        "Jojo Rabbit",
        "Parasite",
        10577
        ],
        "_id": "5e2869d0db9341001700863e",
        "username": "5e2869d0db9341001700863d",
        "date": "2020-01-22T15:27:12.494Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
        ],
        "_id": "5e2874fedb9341001700865c",
        "username": "5e2874fedb9341001700865b",
        "date": "2020-01-22T16:14:54.139Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "1917",
        "American Factory",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
        ],
        "_id": "5e28822adb9341001700866a",
        "username": "5e28822adb93410017008669",
        "date": "2020-01-22T17:11:06.210Z",
        "__v": 0
        },
        {
        "picks": [
        "Adam Driver, Marriage Story",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Saoirse Ronan, Little Women",
        "Laura Dern, Marriage Story",
        "I Lost My Body",
        "1917",
        "Little Women",
        "Parasite",
        "For Sama",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Marriage Story",
        "1917",
        "Kitbull",
        "A Sister",
        "Ford v Ferrari",
        "Ford v Ferrari",
        "The Irishman",
        "Little Women",
        "Marriage Story",
        12289
        ],
        "_id": "5e286a15db93410017008640",
        "username": "5e286a15db9341001700863f",
        "date": "2020-01-22T15:28:21.656Z",
        "__v": 0
        },
        {
        "picks": [
        "Adam Driver, Marriage Story",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Klaus",
        "1917",
        "Joker",
        "1917",
        "The Edge of Democracy",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Jojo Rabbit",
        "Parasite",
        "Joker",
        "Little Women",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Once upon a Time...in Hollywood",
        "Jojo Rabbit",
        "Kitbull",
        "Nefta Football Club",
        "1917",
        "Ford v Ferrari",
        "Star Wars: The Rise of Skywalker",
        "Little Women",
        "Knives Out",
        11568
        ],
        "_id": "5e286aacdb93410017008642",
        "username": "5e286aacdb93410017008641",
        "date": "2020-01-22T15:30:52.695Z",
        "__v": 0
        },
        {
        "picks": [
        "Adam Driver, Marriage Story",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Cynthia Erivo, Harriet",
        "Laura Dern, Marriage Story",
        "I Lost My Body",
        "1917",
        "Little Women",
        "The Irishman",
        "American Factory",
        "Life Overtakes Me",
        "The Irishman",
        "Parasite",
        "Judy",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "The Irishman",
        "Once upon a Time...in Hollywood",
        "Hair Love",
        "The Neighbors' Window",
        "Ford v Ferrari",
        "1917",
        "Star Wars: The Rise of Skywalker",
        "Little Women",
        "Knives Out",
        12075
        ],
        "_id": "5e286b7cdb93410017008646",
        "username": "5e286b7cdb93410017008645",
        "date": "2020-01-22T15:34:20.694Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "I Lost My Body",
        "1917",
        "Little Women",
        "Parasite",
        "Honeyland",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Joker",
        "1917",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "1917",
        "Kitbull",
        "Brotherhood",
        "1917",
        "Ad Astra",
        "1917",
        "Jojo Rabbit",
        "Knives Out",
        13281
        ],
        "_id": "5e286b47db93410017008644",
        "username": "5e286b47db93410017008643",
        "date": "2020-01-22T15:33:27.405Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Saoirse Ronan, Little Women",
        "Florence Pugh, Little Women",
        "Toy Story 4",
        "1917",
        "Little Women",
        "1917",
        "For Sama",
        "Walk Run Cha-Cha",
        "Ford v Ferrari",
        "Parasite",
        "1917",
        "Star Wars: The Rise of Skywalker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "The Irishman",
        "1917",
        "Dcera (Daughter)",
        "The Neighbors' Window",
        "Star Wars: The Rise of Skywalker",
        "1917",
        "Avengers: Endgame",
        "Jojo Rabbit",
        "Once upon a Time...in Hollywood",
        25627
        ],
        "_id": "5e286d8cdb9341001700864a",
        "username": "5e286d8cdb93410017008649",
        "date": "2020-01-22T15:43:08.827Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Joe Pesci, The Irishman",
        "Scarlett Johansson, Marriage Story",
        "Laura Dern, Marriage Story",
        "Missing Link",
        "1917",
        "Little Women",
        "The Irishman",
        "Honeyland",
        "In the Absence",
        "Parasite",
        "Parasite",
        "Joker",
        "Star Wars: The Rise of Skywalker",
        "Into The Unknown, Frozen II",
        "Parasite",
        "1917",
        "Dcera (Daughter)",
        "Saria",
        "1917",
        "1917",
        "1917",
        "The Irishman",
        "Marriage Story",
        13712
        ],
        "_id": "5e286d27db93410017008648",
        "username": "5e286d27db93410017008647",
        "date": "2020-01-22T15:41:27.418Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Florence Pugh, Little Women",
        "Toy Story 4",
        "1917",
        "The Irishman",
        "Parasite",
        "American Factory",
        "Life Overtakes Me",
        "The Irishman",
        "Parasite",
        "1917",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Marriage Story",
        "The Irishman",
        "Kitbull",
        "A Sister",
        "1917",
        "1917",
        "The Irishman",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11907
        ],
        "_id": "5e286deadb9341001700864c",
        "username": "5e286deadb9341001700864b",
        "date": "2020-01-22T15:44:42.806Z",
        "__v": 0
        },
        {
        "picks": [
        "Adam Driver, Marriage Story",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Charlize Theron, Bombshell",
        "Laura Dern, Marriage Story",
        "I Lost My Body",
        "1917",
        "Little Women",
        "Parasite",
        "American Factory",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Bombshell",
        "Star Wars: The Rise of Skywalker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "1917",
        "Hair Love",
        "A Sister",
        "1917",
        "Ad Astra",
        "The Irishman",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11857
        ],
        "_id": "5e286f45db9341001700864e",
        "username": "5e286f45db9341001700864d",
        "date": "2020-01-22T15:50:29.139Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Parasite",
        "The Edge of Democracy",
        "Life Overtakes Me",
        "Parasite",
        "Parasite",
        "Joker",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "1917",
        "Hair Love",
        "A Sister",
        "Ford v Ferrari",
        "Ford v Ferrari",
        "1917",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11516
        ],
        "_id": "5e286fb0db93410017008652",
        "username": "5e286fb0db93410017008651",
        "date": "2020-01-22T15:52:16.785Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Parasite",
        "The Cave",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "The Irishman",
        "Parasite",
        "Bombshell",
        "Joker",
        "Into The Unknown, Frozen II",
        "1917",
        "1917",
        "Kitbull",
        "Saria",
        "1917",
        "Ford v Ferrari",
        "The Lion King",
        "Little Women",
        "Knives Out",
        11843
        ],
        "_id": "5e286f87db93410017008650",
        "username": "5e286f87db9341001700864f",
        "date": "2020-01-22T15:51:35.529Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Joe Pesci, The Irishman",
        "Cynthia Erivo, Harriet",
        "Kathy Bates, Richard Jewell",
        "Toy Story 4",
        "1917",
        "Joker",
        "Parasite",
        "The Cave",
        "St. Louis Superman",
        "Ford v Ferrari",
        "Parasite",
        "Joker",
        "1917",
        "I Can't Let You Throw Yourself Away, Toy Story 4",
        "1917",
        "1917",
        "Hair Love",
        "Brotherhood",
        "1917",
        "1917",
        "1917",
        "Joker",
        "1917",
        10043
        ],
        "_id": "5e287318db93410017008656",
        "username": "5e287318db93410017008655",
        "date": "2020-01-22T16:06:48.986Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Florence Pugh, Little Women",
        "Toy Story 4",
        "1917",
        "Joker",
        "Parasite",
        "The Edge of Democracy",
        "Walk Run Cha-Cha",
        "The Irishman",
        "Parasite",
        "Joker",
        "Little Women",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Once upon a Time...in Hollywood",
        "Memorable",
        "Nefta Football Club",
        "1917",
        "1917",
        "Avengers: Endgame",
        "Joker",
        "Once upon a Time...in Hollywood",
        14823
        ],
        "_id": "5e287328db93410017008658",
        "username": "5e287328db93410017008657",
        "date": "2020-01-22T16:07:04.575Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "1917",
        "Honeyland",
        "In the Absence",
        "The Irishman",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "The Irishman",
        "Once upon a Time...in Hollywood",
        "Memorable",
        "A Sister",
        "1917",
        "1917",
        "Avengers: Endgame",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11430
        ],
        "_id": "5e2873e3db9341001700865a",
        "username": "5e2873e3db93410017008659",
        "date": "2020-01-22T16:10:11.200Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Parasite",
        "For Sama",
        "In the Absence",
        "The Irishman",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Once upon a Time...in Hollywood",
        "Once upon a Time...in Hollywood",
        "Sister",
        "Brotherhood",
        "1917",
        "1917",
        "Avengers: Endgame",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11996
        ],
        "_id": "5e287624db93410017008660",
        "username": "5e287624db9341001700865f",
        "date": "2020-01-22T16:19:48.439Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Missing Link",
        "1917",
        "Little Women",
        "Parasite",
        "For Sama",
        "In the Absence",
        "Ford v Ferrari",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Once upon a Time...in Hollywood",
        "Kitbull",
        "Brotherhood",
        "Ford v Ferrari",
        "Ford v Ferrari",
        "Avengers: Endgame",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11553
        ],
        "_id": "5e28760fdb9341001700865e",
        "username": "5e28760fdb9341001700865d",
        "date": "2020-01-22T16:19:27.886Z",
        "__v": 0
        },
        {
        "picks": [
        "Jonathan Pryce, The Two Popes",
        "Tom Hanks, A Beautiful Day in the Neighborhood",
        "Scarlett Johansson, Marriage Story",
        "Kathy Bates, Richard Jewell",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Parasite",
        "For Sama",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Joker",
        "1917",
        "(I'm Gonna) Love Me Again, Rocketman",
        "The Irishman",
        "Once upon a Time...in Hollywood",
        "Memorable",
        "A Sister",
        "1917",
        "1917",
        "The Lion King",
        "Little Women",
        "Knives Out",
        12162
        ],
        "_id": "5e287829db93410017008662",
        "username": "5e287829db93410017008661",
        "date": "2020-01-22T16:28:25.681Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Once upon a Time...in Hollywood",
        "1917",
        "American Factory",
        "St. Louis Superman",
        "Ford v Ferrari",
        "Parasite",
        "Joker",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Once upon a Time...in Hollywood",
        "Hair Love",
        "Brotherhood",
        "Ford v Ferrari",
        "1917",
        "The Lion King",
        "The Irishman",
        "Once upon a Time...in Hollywood",
        12767
        ],
        "_id": "5e287253db93410017008654",
        "username": "5e287253db93410017008653",
        "date": "2020-01-22T16:03:31.989Z",
        "__v": 0
        },
        {
        "picks": [
        "Leonardo DiCaprio, Once upon a Time...in Hollywood",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Charlize Theron, Bombshell",
        "Florence Pugh, Little Women",
        "How to Train Your Dragon: The Hidden World",
        "1917",
        "Once upon a Time...in Hollywood",
        "1917",
        "The Edge of Democracy",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Maleficent: Mistress of Evil",
        "Marriage Story",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Parasite",
        "Parasite",
        "Sister",
        "The Neighbors' Window",
        "Ford v Ferrari",
        "Once upon a Time...in Hollywood",
        "1917",
        "Jojo Rabbit",
        "Once upon a Time...in Hollywood",
        12466
        ],
        "_id": "5e287c9bdb93410017008664",
        "username": "5e287c9bdb93410017008663",
        "date": "2020-01-22T16:47:23.697Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "1917",
        "American Factory",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Parasite",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Once upon a Time...in Hollywood",
        "Hair Love",
        "Brotherhood",
        "Ford v Ferrari",
        "1917",
        "Avengers: Endgame",
        "Little Women",
        "Once upon a Time...in Hollywood",
        13369
        ],
        "_id": "5e288011db93410017008668",
        "username": "5e288011db93410017008667",
        "date": "2020-01-22T17:02:09.243Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Joe Pesci, The Irishman",
        "Scarlett Johansson, Marriage Story",
        "Margot Robbie, Bombshell",
        "Toy Story 4",
        "1917",
        "Little Women",
        "1917",
        "For Sama",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Bombshell",
        "Star Wars: The Rise of Skywalker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "The Irishman",
        "Once upon a Time...in Hollywood",
        "Kitbull",
        "Saria",
        "Ford v Ferrari",
        "Ford v Ferrari",
        "The Irishman",
        "Little Women",
        "Knives Out",
        13654
        ],
        "_id": "5e287d76db93410017008666",
        "username": "5e287d75db93410017008665",
        "date": "2020-01-22T16:51:02.010Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Tom Hanks, A Beautiful Day in the Neighborhood",
        "Renée Zellweger, Judy",
        "Kathy Bates, Richard Jewell",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Parasite",
        "For Sama",
        "Walk Run Cha-Cha",
        "Ford v Ferrari",
        "Parasite",
        "Bombshell",
        "1917",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "1917",
        "Sister",
        "Nefta Football Club",
        "1917",
        "1917",
        "The Lion King",
        "Little Women",
        "Parasite",
        13612
        ],
        "_id": "5e28827ddb9341001700866c",
        "username": "5e28827ddb9341001700866b",
        "date": "2020-01-22T17:12:29.158Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "1917",
        "American Factory",
        "In the Absence",
        "Ford v Ferrari",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Once upon a Time...in Hollywood",
        "Once upon a Time...in Hollywood",
        "Memorable",
        "Saria",
        "Joker",
        "Joker",
        "The Lion King",
        "Little Women",
        "Parasite",
        11111
        ],
        "_id": "5e288d01db9341001700866e",
        "username": "5e288d01db9341001700866d",
        "date": "2020-01-22T17:57:21.770Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Al Pacino, The Irishman",
        "Charlize Theron, Bombshell",
        "Scarlett Johansson, Jojo Rabbit",
        "Toy Story 4",
        "1917",
        "Joker",
        "1917",
        "The Cave",
        "St. Louis Superman",
        "Ford v Ferrari",
        "Parasite",
        "Maleficent: Mistress of Evil",
        "Star Wars: The Rise of Skywalker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Once upon a Time...in Hollywood",
        "Memorable",
        "The Neighbors' Window",
        "Ford v Ferrari",
        "Ford v Ferrari",
        "Avengers: Endgame",
        "Joker",
        "Knives Out",
        26592
        ],
        "_id": "5e289038db93410017008670",
        "username": "5e289038db9341001700866f",
        "date": "2020-01-22T18:11:04.506Z",
        "__v": 0
        },
        {
        "picks": [
        "Adam Driver, Marriage Story",
        "Al Pacino, The Irishman",
        "Renée Zellweger, Judy",
        "Kathy Bates, Richard Jewell",
        "Klaus",
        "1917",
        "Little Women",
        "The Irishman",
        "The Cave",
        "Walk Run Cha-Cha",
        "The Irishman",
        "Parasite",
        "Bombshell",
        "1917",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "The Irishman",
        "Hair Love",
        "Brotherhood",
        "1917",
        "1917",
        "The Irishman",
        "Little Women",
        "Once upon a Time...in Hollywood",
        16574
        ],
        "_id": "5e289576db93410017008672",
        "username": "5e289576db93410017008671",
        "date": "2020-01-22T18:33:26.849Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Parasite",
        "Honeyland",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "The Irishman",
        "Parasite",
        "Bombshell",
        "1917",
        "Into The Unknown, Frozen II",
        "1917",
        "1917",
        "Kitbull",
        "The Neighbors' Window",
        "Ford v Ferrari",
        "Ford v Ferrari",
        "1917",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11063
        ],
        "_id": "5e289948db93410017008674",
        "username": "5e289948db93410017008673",
        "date": "2020-01-22T18:49:44.816Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Joker",
        "1917",
        "American Factory",
        "In the Absence",
        "Parasite",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Parasite",
        "Once upon a Time...in Hollywood",
        "Kitbull",
        "Saria",
        "Ford v Ferrari",
        "Ford v Ferrari",
        "Avengers: Endgame",
        "Little Women",
        "Parasite",
        11699
        ],
        "_id": "5e289f9bdb93410017008676",
        "username": "5e289f9bdb93410017008675",
        "date": "2020-01-22T19:16:43.522Z",
        "__v": 0
        },
        {
        "picks": [
        "Jonathan Pryce, The Two Popes",
        "Joe Pesci, The Irishman",
        "Charlize Theron, Bombshell",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "The Irishman",
        "Once upon a Time...in Hollywood",
        "The Irishman",
        "The Edge of Democracy",
        "Walk Run Cha-Cha",
        "Joker",
        "Parasite",
        "Bombshell",
        "1917",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Parasite",
        "Kitbull",
        "A Sister",
        "Ford v Ferrari",
        "1917",
        "The Irishman",
        "Joker",
        "Knives Out",
        16583
        ],
        "_id": "5e28a50edb93410017008678",
        "username": "5e28a50edb93410017008677",
        "date": "2020-01-22T19:39:58.921Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Once upon a Time...in Hollywood",
        "The Edge of Democracy",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "The Irishman",
        "Parasite",
        "1917",
        "Joker",
        "Into The Unknown, Frozen II",
        "Parasite",
        "Once upon a Time...in Hollywood",
        "Kitbull",
        "A Sister",
        "1917",
        "1917",
        "The Irishman",
        "The Irishman",
        "Once upon a Time...in Hollywood",
        13871
        ],
        "_id": "5e28b5e2db9341001700867a",
        "username": "5e28b5e2db93410017008679",
        "date": "2020-01-22T20:51:46.760Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Scarlett Johansson, Marriage Story",
        "Laura Dern, Marriage Story",
        "I Lost My Body",
        "1917",
        "Little Women",
        "1917",
        "Honeyland",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Ford v Ferrari",
        "Parasite",
        "Joker",
        "Marriage Story",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Parasite",
        "Kitbull",
        "Nefta Football Club",
        "Once upon a Time...in Hollywood",
        "Ford v Ferrari",
        "Avengers: Endgame",
        "The Two Popes",
        "Parasite",
        12750
        ],
        "_id": "5e28c47bdb9341001700867e",
        "username": "5e28c47bdb9341001700867d",
        "date": "2020-01-22T21:54:03.984Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Jojo Rabbit",
        "1917",
        "For Sama",
        "In the Absence",
        "Parasite",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Parasite",
        "Kitbull",
        "Brotherhood",
        "Ford v Ferrari",
        "Ford v Ferrari",
        "Avengers: Endgame",
        "Little Women",
        "Once upon a Time...in Hollywood",
        11877
        ],
        "_id": "5e28c423db9341001700867c",
        "username": "5e28c423db9341001700867b",
        "date": "2020-01-22T21:52:35.449Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
        ],
        "_id": "5e28cd57db93410017008680",
        "username": "5e28cd57db9341001700867f",
        "date": "2020-01-22T22:31:51.994Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Scarlett Johansson, Jojo Rabbit",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Parasite",
        "American Factory",
        "In the Absence",
        "The Irishman",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Once upon a Time...in Hollywood",
        "Sister",
        "The Neighbors' Window",
        "1917",
        "1917",
        "Avengers: Endgame",
        "Joker",
        "Once upon a Time...in Hollywood",
        12317
        ],
        "_id": "5e28d0ebdb93410017008682",
        "username": "5e28d0ebdb93410017008681",
        "date": "2020-01-22T22:47:07.545Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Charlize Theron, Bombshell",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Once upon a Time...in Hollywood",
        "Once upon a Time...in Hollywood",
        "The Cave",
        "In the Absence",
        "The Irishman",
        "Parasite",
        "Bombshell",
        "1917",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Once upon a Time...in Hollywood",
        "Once upon a Time...in Hollywood",
        "Hair Love",
        "A Sister",
        "1917",
        "Ad Astra",
        "Avengers: Endgame",
        "Little Women",
        "Knives Out",
        12402
        ],
        "_id": "5e28d976db93410017008684",
        "username": "5e28d976db93410017008683",
        "date": "2020-01-22T23:23:34.485Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Joker",
        "Parasite",
        "Honeyland",
        "In the Absence",
        "Parasite",
        "Parasite",
        "Joker",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "1917",
        "Parasite",
        "Hair Love",
        "A Sister",
        "1917",
        "1917",
        "Avengers: Endgame",
        "Little Women",
        "Once upon a Time...in Hollywood",
        10997
        ],
        "_id": "5e28f4e3db93410017008686",
        "username": "5e28f4e3db93410017008685",
        "date": "2020-01-23T01:20:35.050Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Charlize Theron, Bombshell",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Once upon a Time...in Hollywood",
        "1917",
        "The Edge of Democracy",
        "Learning to Skateboard in a Warzone (If You're a Girl)",
        "Parasite",
        "Parasite",
        "Joker",
        "Star Wars: The Rise of Skywalker",
        "I Can't Let You Throw Yourself Away, Toy Story 4",
        "Once upon a Time...in Hollywood",
        "Once upon a Time...in Hollywood",
        "Hair Love",
        "Saria",
        "1917",
        "1917",
        "The Lion King",
        "The Two Popes",
        "Knives Out",
        14052
        ],
        "_id": "5e28fa5ddb93410017008688",
        "username": "5e28fa5ddb93410017008687",
        "date": "2020-01-23T01:43:57.741Z",
        "__v": 0
        },
        {
        "picks": [
        "Joaquin Phoenix, Joker",
        "Brad Pitt, Once upon a Time...in Hollywood",
        "Renée Zellweger, Judy",
        "Laura Dern, Marriage Story",
        "Toy Story 4",
        "1917",
        "Little Women",
        "Parasite",
        "American Factory",
        "In the Absence",
        "Parasite",
        "Parasite",
        "Bombshell",
        "Joker",
        "(I'm Gonna) Love Me Again, Rocketman",
        "Parasite",
        "Once upon a Time...in Hollywood",
        "Hair Love",
        "Saria",
        "1917",
        "1917",
        "The Irishman",
        "Little Women",
        "Once upon a Time...in Hollywood",
        10983
        ],
        "_id": "5e290e2fdb9341001700868a",
        "username": "5e290e2fdb93410017008689",
        "date": "2020-01-23T03:08:31.973Z",
        "__v": 0
        },
        {
        "picks": [
        "Leonardo DiCaprio, Once upon a Time...in Hollywood",
        "Tom Hanks, A Beautiful Day in the Neighborhood",
        "Charlize Theron, Bombshell",
        "Florence Pugh, Little Women",
        "Toy Story 4",
        "1917",
        "Joker",
        "1917",
        "The Edge of Democracy",
        "Walk Run Cha-Cha",
        "Parasite",
        "Parasite",
        "Joker",
        "Little Women",
        "I Can't Let You Throw Yourself Away, Toy Story 4",
        "1917",
        "Once upon a Time...in Hollywood",
        "Sister",
        "Brotherhood",
        "1917",
        "Once upon a Time...in Hollywood",
        "Avengers: Endgame",
        "The Irishman",
        "Knives Out",
        14503
        ],
        "_id": "5e291c9fdb9341001700868c",
        "username": "5e291c9fdb9341001700868b",
        "date": "2020-01-23T04:10:07.723Z",
        "__v": 0
        },
        {
        "picks": [
        "Leonardo DiCaprio, Once upon a Time...in Hollywood",
        "Tom Hanks, A Beautiful Day in the Neighborhood",
        "Saoirse Ronan, Little Women",
        "Scarlett Johansson, Jojo Rabbit",
        "Toy Story 4",
        "1917",
        "Once upon a Time...in Hollywood",
        "Once upon a Time...in Hollywood",
        "Honeyland",
        "In the Absence",
        "Ford v Ferrari",
        "Honeyland",
        "Joker",
        "Star Wars: The Rise of Skywalker",
        "Into The Unknown, Frozen II",
        "Jojo Rabbit",
        "1917",
        "Sister",
        "Brotherhood",
        "Ford v Ferrari",
        "1917",
        "Avengers: Endgame",
        "Jojo Rabbit",
        "Once upon a Time...in Hollywood",
        15930
        ],
        "_id": "5e29247adb9341001700868e",
        "username": "5e29247adb9341001700868d",
        "date": "2020-01-23T04:43:38.278Z",
        "__v": 0
        }
    ],
};